# Generated by Django 2.0.5 on 2018-06-02 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='afiliado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=200)),
                ('aldea', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('dpi', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('fotografia', models.ImageField(upload_to='fotografia/afiliado/')),
                ('genero', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('cuota', models.BooleanField()),
                ('baja', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=200)),
                ('aldea', models.CharField(max_length=100)),
                ('municipio', models.CharField(choices=[('Comitancillo', 'Comitancillo'), ('San Lorenzo', 'San Lorenzo')], max_length=12)),
                ('celular', models.CharField(max_length=15)),
                ('dpi', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('fotografia', models.ImageField(upload_to='fotografia/empleado/')),
                ('genero', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('puesto', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(default='2018/06/02', max_length=50)),
                ('hora', models.CharField(default='03:15:26', max_length=50)),
                ('lugar', models.CharField(choices=[('Comitancillo', 'Comitancillo'), ('San Lorenzo', 'San Lorenzo')], max_length=12)),
                ('tratamiento', models.CharField(choices=[('Rellenos', 'Rellenos'), ('T. de canales', 'T. de canales'), ('Limpieza', 'Limpieza'), ('Extracciones', 'Extracciones')], max_length=15)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.afiliado')),
                ('employ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rol.empleado')),
            ],
        ),
    ]
